.travis.yml
Gemfile
lib/telegram/bot/middleware.rb
lib/telegram/bot/updates_controller.rb
spec/telegram/bot/middleware_spec.rb
spec/telegram/bot/updates_controller_spec.rb

Rails5 compatibility

---

telegram-bot.gemspec

- Add support `activesupport 5.1`
- Add support `actionpack 5.1`
As mentioned in #27

Increase dependencies version

---

.gitignore
CHANGELOG.md
Gemfile
lib/telegram/bot/client_stub.rb
lib/telegram/bot/rspec/integration.rb
spec/integration/requests/default_bot_spec.rb
spec/integration/requests/other_bot_spec.rb
spec/integration_helper.rb
spec/telegram/bot/client_stub_spec.rb
spec/telegram/bot/config_methods_spec.rb

Integration test with rails app and two bots

---

.travis.yml
Appraisals
config/credentials.yml.enc
config/master.key
gemfiles/rails_42.gemfile
gemfiles/rails_51.gemfile
gemfiles/rails_52.gemfile
lib/telegram/bot/config_methods.rb
spec/integration_helper.rb

User Rails.application.credentials if defined

Support for :credentials on Rails v5.2.x.

---

README.md

Thought I'd suggest some edits based on grammar and some spelling mistakes considering how useful this Bot has been for the project I'm working on. Feel free to ignore if it's not needed.

Testing Cleanup

---

README.md

Regarding Botan.io https://github.com/botanio/sdk#this-service-will-be-shut-down-on-25th-may-2018

Changed README a bit

---

lib/telegram/bot/updates_controller/reply_helpers.rb

I have added the missing helper method `answer_pre_check_query` and it works right now.
If you need anymore help please comment on it.
fixes #117

Pre checkout query

---

.travis.yml
Appraisals
CHANGELOG.md
gemfiles/rails_42.gemfile
gemfiles/rails_51.gemfile
gemfiles/rails_52.gemfile
gemfiles/rails_60.gemfile
gemfiles/rails_61.gemfile
telegram-bot.gemspec

Require tests against rails 6.0, run tests against rails 6.1.alpha

---

.travis.yml
Appraisals
gemfiles/rails_61.gemfile
lib/telegram/bot/updates_controller/instrumentation.rb
telegram-bot.gemspec

Add rails 6.1 support

---

.travis.yml
CHANGELOG.md
Gemfile
gemfiles/rails_42.gemfile
gemfiles/rails_50.gemfile
gemfiles/rails_51.gemfile
gemfiles/rails_52.gemfile
gemfiles/rails_60.gemfile
gemfiles/rails_61.gemfile
lib/telegram/bot/client_stub.rb
spec/support/examples/async.rb
spec/telegram/bot/client_spec.rb
spec/telegram/bot/client_stub_spec.rb
spec/telegram/bot/routes_helper_spec.rb
telegram-bot.gemspec

Ruby 3.0 support

---

lib/telegram/bot/updates_controller/translation.rb
spec/telegram/bot/updates_controller/translation_spec.rb

Fix translation helpers to support ruby 3

---

CHANGELOG.md
Gemfile
lib/telegram/bot/client/api_methods.txt
lib/telegram/bot/updates_controller.rb
lib/telegram/bot/version.rb
spec/telegram/bot/updates_controller/typed_update_spec.rb

Update to Bot API 5.3

---

Appraisals
CHANGELOG.md
gemfiles/rails_42.gemfile
gemfiles/rails_50.gemfile
gemfiles/rails_52.gemfile
gemfiles/rails_60.gemfile
gemfiles/rails_61.gemfile
gemfiles/rails_70.gemfile
telegram-bot.gemspec

Rails 7.0 support

---

CHANGELOG.md
lib/telegram/bot/client.rb
lib/telegram/bot/client/request_body_formatter.rb
spec/telegram/bot/client/request_body_formatter_spec.rb
spec/telegram/bot/client_spec.rb

Fix sending File objects in nested objects (ex., in sendMediaGroup)

---

CHANGELOG.md
lib/telegram/bot/client/request_body_formatter.rb
lib/telegram/bot/version.rb
spec/telegram/bot/client/request_body_formatter_spec.rb

Add support for editMessageMedia similar to sendMediaGroup

---

lib/telegram/bot/client/api_methods.txt

Used `fetch-telegram-methods` script

Add new commands available at API 6.8

---

CHANGELOG.md
README.md
lib/telegram/bot/middleware.rb
lib/telegram/bot/updates_controller.rb
lib/telegram/bot/updates_controller/rspec_helpers.rb
lib/telegram/bot/updates_controller/testing.rb
lib/telegram/bot/updates_controller/typed_update.rb
spec/integration/requests/default_bot_spec.rb
spec/telegram/bot/middleware_spec.rb
spec/telegram/bot/rspec/integration/poller_spec.rb
spec/telegram/bot/rspec/integration/rack_spec.rb
spec/telegram/bot/updates_controller/testing_spec.rb

Add UpdatesController#webhook_request

---

lib/telegram/bot/rspec/client_matchers.rb
lib/telegram/bot/updates_controller/log_subscriber.rb
spec/telegram/bot/rspec/client_matchers_spec.rb

Fix frozen string issue for ruby < 3

---

lib/telegram/bot/client/api_methods.txt

- Add new method: `sendPaidMedia`

Update Bot API version from 7.5 to 7.7

---

CHANGELOG.md
lib/telegram/bot/client/api_methods.txt
lib/telegram/bot/updates_controller.rb
spec/telegram/bot/updates_controller/typed_update_spec.rb
spec/telegram/bot/updates_controller_spec.rb

- Added pre_checkout_query to updates_controller.rb
- Updated tests in updates_controller_spec.rb
- Updated tests in typed_update_spec.rb
- Updated CHANGELOG.md for Bot API 7.7 and pre_checkout_query

Add pre_checkout_query to PAYLOAD_TYPES
